on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: login to dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: build image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/nurda:latest .

    - name: push to dockerhub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/nurda:latest
  
  deploy-1:
    runs-on: ubuntu-latest
    needs: build 
    steps:
    - name: deploy
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/github_actions
        chmod 600 ~/.ssh/github_actions
        
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/github_actions ubuntu@3.231.210.164 << '#'
        
        sudo docker stop nurda || true
        sudo docker rm nurda || true

        sudo docker pull ${{ secrets.DOCKER_USERNAME }}/nurda:latest

        sudo docker run -d --name nurda -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/nurda:latest
        #
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}

    - name: successful completion
      run: echo "Deployment to EC2 complete."
