on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: login to dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: build image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/nurda:latest .

    - name: push to dockerhub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/nurda:latest
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 3.231.210.164
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          sudo docker stop nurda  true
          sudo docker rm nurda  true
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/nurda:latest
          sudo docker run -d --name nurda -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/nurda:latest


    - name: successful completion
      run: echo "Deployment to EC2 complete."
